# Cấu hình Server
server:
  port: 8080

spring:
  # Cấu hình kết nối MySQL
  datasource:
    url: jdbc:mysql://localhost:3306/HotelDB_Schema?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: Monkeydthang2476@
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Cấu hình gửi mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: myeternity001@gmail.com
    password: svmp rbwn xsnq cdnw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # Cấu hình JPA / Hibernate
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Cấu hình đường dẫn cho Swagger
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

# JWT
jwt:
  secret: ${JWT_SECRET:this-is-a-256-bit-secret-key-for-hms-project-change-in-production!!}
  expiration: 86400000
